<?php

namespace App\Models;
use App\Book;
use App\book_user;
use App\Education;
use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use Laravel\Lumen\Auth\Authorizable;
use Spatie\Permission\Traits\HasPermissions;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Spatie\Permission\Traits\HasRoles;

class User extends Model implements AuthenticatableContract, AuthorizableContract,JWTSubject
{

    use Authenticatable, Authorizable, HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email','last_name','birthday','gender','image','age','date_login',
        'education_id','password'
    ];

//    public static function boot()
//    {
//        {
//            parent::boot(); // TODO: Change the autogenerated stub
//
//            self::creating(function ($model) {
//                $model->password = Hash::make('12345678');
//            });
//        }
//
//    }*/ if you want  can use password default*/
    protected $hidden = [
        'password',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }
    public function getJWTCustomClaims()
    {
        return [];
    }
    public function education(){

        return $this->hasOne(Education::class);

    }
    public function books(){
        return $this->hasMany(Book::class);
    }
    public function bookmarks(){
        return $this->belongsToMany(Book::class,'book_user','user_id','book_id');
    }
    public function like_books(){
        return $this->belongsToMany(User::class,'book_user_like','user_id','book_id')->withTimestamps();
    }

    protected $guard_name = 'api';
}
